apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carriercarriermember-node
  namespace: carrier-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carriercarriermember-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_besu
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    metadata:
      namespace: carrier-bes
      labels:
    replicaCount: 1
    staticnodes:
      - "enode://1ce49dbeb8a3a2a201bd88a0528be9b4f99beb3aba4f203656db83d6fcaf4b4efc056505a8ccd396870f51bfb267709e6a53c98fd8e932c42c40bed7a0129efe@validator1.supplychain-bes.svc.cluster.local:30303"
      - "enode://8a37586c637ab7db9ce564e0e1053bce592465171e8740c3ec35616d0ecde73096e650ef9a26c611cf8e5aa752fcca485a5379d6b36fc9213c2da9f2c7371c1a@validator2.supplychain-bes.svc.cluster.local:30303"
      - "enode://58ed0cdeb9e7e19c6afb4684c5835939ffd98746a66905d7fc3157b794aae7c96fa388650735c75f6a226b0c67a9ab7e650ae9ee4ae444da9a18db3e21aca388@validator3.supplychain-bes.svc.cluster.local:30303"
      - "enode://201f78c2a762e59b85fb96e18d1ed8a3a7c94e6e7e83f163b42a480078e8e23fb611c8cf5f694ae4d5636ecfbc0e404da288722641da3ffaa3e493f0c084dd96@validator4.supplychain-bes.svc.cluster.local:30303"
      - "enode://b8479234f1056c0885cb32e09dcc93fd2f06c2d9b46c86131b9782a70c77ef90239ddb92e7de489522c0ed6ff6280b4f4ff292004adc9aa8ea8d351054b7b6ca@carrier.carrier-bes.svc.cluster.local:30303"

    liveliness_check:
      enabled: false
    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5
    proxy:
      provider: none
      external_url: carrier.carrier-bes
      p2p: 30303
      rpc: 8545

    images:
      node: hyperledger/besu:21.10.6
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullPolicy: IfNotPresent

    node:
      name: carrier
      consensus: ibft
      subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

      permissioning:
        enabled: False

    tm:
      type: tessera
      tls: True
      url: "https://carrier-tessera.carrier-bes:8888"

    privacy:
      enabled: true
      public_key_file: /secrets/tm_key.pub
      tm_flag: true

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://172.21.122.44:8200
      secretengine: secretsv2
      secretprefix: data/carrier-bes/crypto/carrier
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      type: hashicorp
      authpath: besucarrier

    genesis: 

   
    labels:  
      service:
        - component: besu
      pvc:
      deployment:
        - owner: bevel
        - component: besu
 

    metrics:
      enabled: False
      port: 9545
